//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description StartDetails related to the Current Status of a Container will go here
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Service {
    using CamstarClient.Enum;
    using CamstarClient.Entity;
    
    public class CurrentStatusStartDetails : ServiceData {
        public StepRef WorkflowStep {
            get; set;
        }
        public WorkflowRef Workflow {
            get; set;
        }
    }
}
