//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Steps are used to discretely define processing for a point (step) within a Workflow. A Workflow is a collection of Steps that are related using Paths. Each Step contains zero or more Paths, which link to another Step. One Path at each Step is identified as the default Path.
///
///A sequence of Steps and Paths is a Route. A Workflow can include multiple Routes. Only one Route is identified as the Standard Route. The Standard Route is determined by starting with the Step that is identified as the first Step and then iterating forward selecting the default path at each step.
///
///A Specification Step is a step within a Workflow that includes a reference to a Spec which in turn describes the work that is to be performed.
///
///
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [Table("WORKFLOWSTEP")]
    public class SpecStep : Step {
        public virtual Spec Spec {
            get; set;
        }
        [Column("SEQUENCE")]
        public System.Nullable<int> Sequence {
            get; set;
        }
        [Column("WORKFLOWSTEPNAME")]
        public string Name {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
        [Column("STEPTYPE")]
        public System.Nullable<int> StepType {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("ISROUTESTEPNAME")]
        public string isRouteStepName {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId
        {
            get; set;
        }
        [Column("ISLASTSTEP")]
        public System.Nullable<bool> IsLastStep
        {
            get; set;
        }
        [Column("WORKFLOWSTEPID")]
        [Key()]
        public string InstanceID
        {
            get; set;
        }
    }
}
