//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///     @author lichong\n    @date 2024/3/24
///
namespace CamstarClient.Service {
    
    public class StepRef {
        public string Name {
            get; set;
        }
    }
}
