//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("CONTDEFECTREASONGROUP")]
    public class ContainerDefectReasonGroup : UserCodeGroup
    {
        public virtual ICollection<ContainerDefectReasonGroup> Groups {
            get; set;
        }
        public virtual ICollection<ContainerDefectReason> Entries {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public int ChangeCount {
            get; set;
        }
        [Column("DEFECTREASONGROUPID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("DEFECTREASONGROUPNAME")]
        public string Name {
            get; set;
        }
        [Column("ISFROZEN")]
        public bool IsFrozen {
            get; set;
        }
        [Column("ICONID")]
        public int IconId {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("ENTRYTYPE")]
        public string EntryType {
            get; set;
        }
        [Column("CDOTYPEID")]
        public int CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
    }
}
