//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/23
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("SPEC")]
    public class Spec : BusinessProcessSpec {
        public virtual Operation Operation {
            get; set;
        }
        public virtual ResourceGroup ResourceGroup {
            get; set;
        }
        [Column("MAXQUEUETIME")]
        public System.Nullable<double> MaxQueueTime {
            get; set;
        }
        [Column("WARNINGQUEUETIME")]
        public System.Nullable<double> WarningQueueTime {
            get; set;
        }
        public new virtual SpecBase Base {
            get; set;
        }
        [Column("SPECREVISION")]
        public new string Revision {
            get; set;
        }
        [Column("STATUS")]
        public new StatusEnum Status {
            get; set;
        }
        [Column("DESCRIPTION")]
        public new string Description {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public new System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("SPECID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        [Column("CDOTYPEID")]
        public new System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public new string Notes {
            get; set;
        }
        [Column("AUTODISASSOCIATE")]
        public System.Nullable<bool> AutoDisassociate {
            get; set;
        }
        public virtual IssueDifferenceReason DefaultIssueDifferenceReason {
            get; set;
        }
        [Column("AUTOCLOSE")]
        public System.Nullable<bool> AutoClose {
            get; set;
        }
        public virtual MfgLine MfgLine {
            get; set;
        }
        [Column("AUTOCOMPONENTISSUE")]
        public System.Nullable<bool> AutoComponentIssue {
            get; set;
        }
        [Column("ISMATERIALISSUE")]
        public System.Nullable<bool> IsMaterialIssue {
            get; set;
        }
    }
}
