//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("SPEC")]
    public class Spec : BusinessProcessSpec {
        public virtual Operation Operation {
            get; set;
        }
        public virtual ResourceGroup ResourceGroup {
            get; set;
        }
        [Column("MAXQUEUETIME")]
        public double MaxQueueTime {
            get; set;
        }
        [Column("WARNINGQUEUETIME")]
        public double WarningQueueTime {
            get; set;
        }
        public new virtual SpecBase Base {
            get; set;
        }
        [Column("SPECID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        [Column("AUTODISASSOCIATE")]
        public bool AutoDisassociate {
            get; set;
        }
        public virtual IssueDifferenceReason DefaultIssueDifferenceReason {
            get; set;
        }
        [Column("AUTOCLOSE")]
        public bool AutoClose {
            get; set;
        }
        public virtual MfgLine MfgLine {
            get; set;
        }
        [Column("AUTOCOMPONENTISSUE")]
        public bool AutoComponentIssue {
            get; set;
        }
        [Column("ISMATERIALISSUE")]
        public bool IsMaterialIssue {
            get; set;
        }
    }
}
