//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description The RevisionBase holds information common to all revisions of an object, plus information on which revision is the revision of record.  WorkflowBase is the specific type of RevisionBase used for a workflow, which defines the route and processing details required for a manufacturing process.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [Table("WORKFLOWBASE")]
    public class WorkflowBase : BusinessProcessWorkflowBase {
        [Column("WORKFLOWNAME")]
        public string Name {
            get; set;
        }
        public virtual Workflow RevOfRcd {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("WORKFLOWBASEID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
    }
}
