//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("MFGORDERMATERIALLISTITEM")]
    public class MfgOrderMaterialListItem : ERPMaterialListItem {
        public new virtual UOM UOM {
            get; set;
        }
        public new virtual Product Product {
            get; set;
        }
        [Column("MFGORDERMATERIALLISTITEMID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        public new virtual BaseObject Parent {
            get; set;
        }
        public new virtual Spec Spec {
            get; set;
        }
    }
}
