//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/23
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("USERATTRIBUTE")]
    public class UserAttribute : NamedSubentity {
        [Column("ISEXPRESSION")]
        public System.Nullable<bool> IsExpression {
            get; set;
        }
        [Column("ATTRIBUTEVALUE")]
        public string AttributeValue {
            get; set;
        }
        [Column("CDOTYPEID")]
        public new System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("DATATYPE")]
        public TrivialTypeEnum DataType {
            get; set;
        }
        [Column("USERATTRIBUTEID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public new System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("USERATTRIBUTENAME")]
        public new string Name {
            get; set;
        }
    }
}
