//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Represents a particular material that is required to complete a given manufacturing or assembly step, as defined by the ERP RouteStep refenced in the current WorkflowStep of the container.  The necessary quantities or proportions of the item are specified as are the appropriate units of measure.  This particular type of material list item is used on Mfg orders, and was created so that MfgOrder component lists could be stored in a separate table from BOM or Container component lists.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [Table("MFGORDERMATERIALLISTITEM")]
    public class MfgOrderMaterialListItem : ERPMaterialListItem {
        public virtual RouteStep RouteStep {
            get; set;
        }
        [Column("EFFECTIVEFROMDATE")]
        public System.Nullable<System.DateTime> EffectiveFromDate {
            get; set;
        }
        [Column("EFFECTIVETHRUDATE")]
        public System.Nullable<System.DateTime> EffectiveThruDate {
            get; set;
        }
        [Column("ISSUECONTROL")]
        public IssueControlEnum IssueControl {
            get; set;
        }
        [Column("QTYREQUIRED")]
        public System.Nullable<double> QtyRequired {
            get; set;
        }
        [Column("REFERENCEDESIGNATOR")]
        public string ReferenceDesignator {
            get; set;
        }
        [Column("SCRAPPERCENT")]
        public System.Nullable<double> ScrapPercent {
            get; set;
        }
        [Column("SETUPQTY")]
        public System.Nullable<double> SetupQty {
            get; set;
        }
        public virtual UOM UOM {
            get; set;
        }
        [Column("VENDORCONTROL")]
        public System.Nullable<bool> VendorControl {
            get; set;
        }
        [Column("ALLOWSUBSTITUTION")]
        public System.Nullable<bool> AllowSubstitution {
            get; set;
        }
        [Column("ISENABLED")]
        public System.Nullable<bool> IsEnabled {
            get; set;
        }
        [Column("ERPLINEITEM")]
        public string ERPLineItem {
            get; set;
        }
        public virtual Product Product {
            get; set;
        }
        [Column("ALLOWOVERCONSUMPTION")]
        public System.Nullable<bool> AllowOverConsumption {
            get; set;
        }
        [Column("ALLOWUNDERCONSUMPTION")]
        public System.Nullable<bool> AllowUnderConsumption {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("MFGORDERMATERIALLISTITEMID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        public virtual MfgOrder Parent {
            get; set;
        }
        [Column("MFGORDERMATERIALLISTITEMNAME")]
        public string Name {
            get; set;
        }
        public virtual Spec Spec {
            get; set;
        }
    }
}
