//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description StartDetails describes the attributes of the container about to be started.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Service {
    using CamstarClient.Enum;
    using CamstarClient.Entity;
    
    public class StartDetails : ServiceDetails {
        public ProductRef Product {
            get; set;
        }
        public System.Nullable<double> Qty {
            get; set;
        }
        public CustomerRef Customer {
            get; set;
        }
        public ContainerStatusEnum Status {
            get; set;
        }
        public string ContainerName {
            get; set;
        }
    }
}
