//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("CONTAINERLEVEL")]
    public class ContainerLevel : NamedDataObject
    {
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
        [Column("ALLOWMOVE")]
        public bool AllowMove {
            get; set;
        }
        public virtual ICollection<ContainerLevel> ParentLevels {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public int ChangeCount {
            get; set;
        }
        [Column("CONTAINERLEVELID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CONTAINERLEVELNAME")]
        public string Name {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("CDOTYPEID")]
        public int CDOTypeId {
            get; set;
        }
    }
}
