//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/23
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("EMPLOYEE")]
    public class Employee : NamedDataObject {
        [Column("EMPLOYEEID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        [Column("EMPLOYEENAME")]
        public new string Name {
            get; set;
        }
        [Column("DESCRIPTION")]
        public new string Description {
            get; set;
        }
        [Column("NOTES")]
        public new string Notes {
            get; set;
        }
        [Column("FULLNAME")]
        public string FullName {
            get; set;
        }
        [Column("USERCOMMENT")]
        public string UserComment {
            get; set;
        }
        [Column("CANLOGIN")]
        public System.Nullable<bool> CanLogin {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public new System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("CDOTYPEID")]
        public new System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("DOMAINNAME")]
        public string DomainName {
            get; set;
        }
    }
}
