//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("EMPLOYEE")]
    public class Employee : NamedDataObject
    {
        public virtual SessionValues SessionValues {
            get; set;
        }
        [Column("EMPLOYEEID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("EMPLOYEENAME")]
        public string Name {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
        [Column("FULLNAME")]
        public string FullName {
            get; set;
        }
        [Column("USERCOMMENT")]
        public string UserComment {
            get; set;
        }
        [Column("CANLOGIN")]
        public bool CanLogin {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public int ChangeCount {
            get; set;
        }
        [Column("CDOTYPEID")]
        public int CDOTypeId {
            get; set;
        }
        [Column("DOMAINNAME")]
        public string DomainName {
            get; set;
        }
    }
}
