//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("MFGORDER")]
    public class MfgOrder :NamedDataObject {
        [Column("QTY")]
        public double Qty {
            get; set;
        }
        public virtual Product Product {
            get; set;
        }
        public virtual ProductBase ProductBase
        {
            get; set;
        }
        public virtual UOM UOM {
            get; set;
        }
        [Column("MFGORDERID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("MFGORDERNAME")]
        public string Name {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public int ChangeCount {
            get; set;
        }
        [Column("CDOTYPEID")]
        public int CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
        [Column("PLANNEDSTARTDATE")]
        public System.DateTime PlannedStartDate {
            get; set;
        }
        [Column("PLANNEDCOMPLETIONDATE")]
        public System.DateTime PlannedCompletionDate {
            get; set;
        }
        [Column("RELEASEDATE")]
        public System.DateTime ReleaseDate {
            get; set;
        }
        public virtual OrderType OrderType {
            get; set;
        }
        public virtual OrderStatus OrderStatus {
            get; set;
        }
        [Column("QTYSTARTED")]
        public double QtyStarted {
            get; set;
        }
        [Column("LASTCHANGEDATE")]
        public System.DateTime LastChangeDate {
            get; set;
        }
        public virtual MfgLine MfgLine {
            get; set;
        }
    }
}
