//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public abstract class NamedDataObject : BaseObject {
        public string Name {
            get; set;
        }
        public string Description {
            get; set;
        }
        public string InstanceID {
            get; set;
        }
        public string Notes {
            get; set;
        }
        public int ChangeCount {
            get; set;
        }
        public int CDOTypeId {
            get; set;
        }
    }
}
