//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/23
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("OPERATION")]
    public class Operation : NamedDataObject {
        public virtual WorkCenter WorkCenter {
            get; set;
        }
        public virtual LossReasonGroup LossReasons {
            get; set;
        }
        public virtual ContainerDefectReasonGroup ContainerDefectReasons {
            get; set;
        }
        public virtual ComponentDefectReasonGroup ComponentDefectReasons {
            get; set;
        }
        [Column("OPERATIONNAME")]
        public new string Name {
            get; set;
        }
        [Column("DESCRIPTION")]
        public new string Description {
            get; set;
        }
        public virtual BuyReasonGroup BuyReasons {
            get; set;
        }
        public virtual QtyAdjustReasonGroup QtyAdjustReasons {
            get; set;
        }
        [Column("USEQUEUE")]
        public System.Nullable<bool> UseQueue {
            get; set;
        }
        public virtual ContainerLevel ThruputReportingLevel {
            get; set;
        }
        public virtual ObjectGroup AutoAdjustReason {
            get; set;
        }
        [Column("AUTOADJUSTLIMIT")]
        public System.Nullable<double> AutoAdjustLimit {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public new System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("OPERATIONID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        [Column("CDOTYPEID")]
        public new System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public new string Notes {
            get; set;
        }
        public virtual PrintQueue PrintQueue {
            get; set;
        }
    }
}
