//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("RESOURCEGROUP")]
    public class ResourceGroup : NamedObjectGroup {
        public new virtual ICollection<Resource> Entries {
            get; set;
        }
        public new virtual ICollection<ResourceGroup> Groups {
            get; set;
        }
        [Column("RESOURCEGROUPID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        [Column("OBJECTCATEGORY")]
        public string ObjectCategory {
            get; set;
        }
        [Column("OBJECTTYPE")]
        public string ObjectType {
            get; set;
        }
    }
}
