//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/23
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("USERCODEGROUP")]
    public class UserCodeGroup : NamedObjectGroup {
        [Column("CHANGECOUNT")]
        public new System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("USERCODEGROUPID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        [Column("USERCODEGROUPNAME")]
        public new string Name {
            get; set;
        }
        [Column("ISFROZEN")]
        public new System.Nullable<bool> IsFrozen {
            get; set;
        }
        [Column("ICONID")]
        public new System.Nullable<int> IconId {
            get; set;
        }
        [Column("DESCRIPTION")]
        public new string Description {
            get; set;
        }
        public new virtual ICollection<UserCode> Entries {
            get; set;
        }
        [Column("ENTRYTYPE")]
        public new string EntryType {
            get; set;
        }
        public new virtual ICollection<UserCodeGroup> Groups {
            get; set;
        }
        [Column("CDOTYPEID")]
        public new System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public new string Notes {
            get; set;
        }
    }
}
