//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("CURRENTSTATUS")]
    public class CurrentStatus : BaseObject{
        [Column("CURRENTSTATUSID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        public virtual Factory Factory {
            get; set;
        }
        public virtual Resource Resource {
            get; set;
        }
        public virtual SpecStep WorkflowStep {
            get; set;
        }
        [Column("LASTMOVEDATE")]
        public System.DateTime LastMoveDate {
            get; set;
        }
        [Column("INPROCESS")]
        public bool InProcess {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public int ChangeCount {
            get; set;
        }
        public virtual Spec Spec {
            get; set;
        }
        [Column("INREWORK")]
        public bool InRework {
            get; set;
        }
        [Column("CDOTYPEID")]
        public int CDOTypeId {
            get; set;
        }
        [Column("INQUEUETIME")]
        public double InQueueTime {
            get; set;
        }
        [Column("ISRESOURCENAME")]
        public string isResourceName {
            get; set;
        }
        [Column("ISWORKFLOWSTEPNAME")]
        public string isWorkflowStepName {
            get; set;
        }
        [Column("ISWORKFLOWNAME")]
        public string isWorkflowName {
            get; set;
        }
        [Column("ISSPECREVISION")]
        public string isSpecRevision {
            get; set;
        }
        [Column("ISWORKFLOWREVISION")]
        public string isWorkflowRevision {
            get; set;
        }
        [Column("ISWORKFLOWSTEPSEQUENCE")]
        public int isWorkflowStepSequence {
            get; set;
        }
        [Column("ISSPECNAME")]
        public string isSpecName {
            get; set;
        }
        [Column("ISFACTORYNAME")]
        public string isFactoryName {
            get; set;
        }
        [Column("ISOPERATIONNAME")]
        public string isOperationName {
            get; set;
        }
        [Column("ISOPSTARTQTY")]
        public double isOpStartQty {
            get; set;
        }
        [Column("LASTMOVEOUTDATE")]
        public System.DateTime LastMoveOutDate {
            get; set;
        }
        [Column("MOVEINDATE")]
        public System.DateTime MoveInDate {
            get; set;
        }
    }
}
