//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("HISTORYMAINLINE")]
    public class HistoryMainline : BaseObject {
        [Column("HISTORYMAINLINEID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        public virtual BaseObject TxnId {
            get; set;
        }
        [Column("STATUS")]
        public StatusEnum Status {
            get; set;
        }
        [Column("TXNDATE")]
        public System.DateTime TxnDate {
            get; set;
        }
        [Column("SYSTEMDATE")]
        public System.DateTime SystemDate {
            get; set;
        }
        public virtual Factory Factory {
            get; set;
        }
        public virtual Employee Employee {
            get; set;
        }
        [Column("CLIENT")]
        public int Client {
            get; set;
        }
        [Column("SERVER")]
        public int Server {
            get; set;
        }
        public virtual Container Container {
            get; set;
        }
        public virtual Operation Operation {
            get; set;
        }
        public virtual Resource Resource {
            get; set;
        }
        [Column("COMMENTS")]
        public string Comments {
            get; set;
        }
        public virtual BaseObject HistoryId {
            get; set;
        }
        public virtual Owner Owner {
            get; set;
        }
        public virtual Product Product {
            get; set;
        }
        [Column("INREWORK")]
        public bool InRework {
            get; set;
        }
        public virtual SpecStep WorkflowStep {
            get; set;
        }
        public virtual Spec Spec {
            get; set;
        }
        [Column("TXNTYPENAME")]
        public string TxnTypeName {
            get; set;
        }
        public virtual Container ParentContainer {
            get; set;
        }
        [Column("PARENTCONTAINERNAME")]
        public string ParentContainerName {
            get; set;
        }
        [Column("TOQTY")]
        public double ToQty {
            get; set;
        }
        [Column("QTY")]
        public double Qty {
            get; set;
        }
        [Column("MOVEINQTY")]
        public double MoveInQty {
            get; set;
        }
        [Column("LASTMOVEOUTDATE")]
        public System.DateTime LastMoveOutDate {
            get; set;
        }
        [Column("TXNSEQUENCE")]
        public int TxnSequence {
            get; set;
        }
        [Column("CHILDCOUNT")]
        public int ChildCount {
            get; set;
        }
        [Column("CONTAINERNAME")]
        public string ContainerName {
            get; set;
        }
        [Column("MOVEINDATE")]
        public System.DateTime MoveInDate {
            get; set;
        }
        [Column("SERVERNAME")]
        public string ServerName {
            get; set;
        }
        [Column("COMPUTERNAME")]
        public string ComputerName {
            get; set;
        }
    }
}
