//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/23
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("WORKFLOWSTEP")]
    public class SpecStep : Step {
        public virtual Spec Spec {
            get; set;
        }
        [Column("SEQUENCE")]
        public new System.Nullable<int> Sequence {
            get; set;
        }
        [Column("WORKFLOWSTEPNAME")]
        public new string Name {
            get; set;
        }
        [Column("DESCRIPTION")]
        public new string Description {
            get; set;
        }
        [Column("NOTES")]
        public new string Notes {
            get; set;
        }
        [Column("STEPTYPE")]
        public new System.Nullable<int> StepType {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public new System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("ISROUTESTEPNAME")]
        public string isRouteStepName {
            get; set;
        }
        [Column("WORKFLOWSTEPID")]
        [Key()]
        public new string InstanceID
        {
            get; set;
        }
        [Column("ISLASTSTEP")]
        public System.Nullable<bool> IsLastStep
        {
            get; set;
        }
        [Column("CDOTYPEID")]
        public new System.Nullable<int> CDOTypeId
        {
            get; set;
        }
    }
}
