//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/23
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [NotMapped()]
    public abstract class BusinessProcessWorkflowBase : RevisionBase {
        public new System.Nullable<int> CDOTypeId {
            get; set;
        }
        public new string InstanceID {
            get; set;
        }
        public new System.Nullable<int> ChangeCount {
            get; set;
        }
        public new virtual BusinessProcessWorkflow RevOfRcd {
            get; set;
        }
        public new string Name {
            get; set;
        }
    }
}
