//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description A specification (Spec) describes the processing that takes place at a Step within a Workflow. It references many other Modeling components including an Operation, Setup, Data Collection Definitions and Resources. Specs also include detailed scheduling and processing parameter information. A Spec is referenced (used) by a Step within a Workflow. Many Workflow Steps can use one Spec.
///
///A Spec is used to define the processing that is to be performed. An Operation is used to define (rules for) the flow or movement of Material through the Factory.
///
///See the Operation Definition for Scheduling Details information.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [Table("SPEC")]
    public class Spec : BusinessProcessSpec {
        public virtual Operation Operation {
            get; set;
        }
        public virtual ResourceGroup ResourceGroup {
            get; set;
        }
        [Column("MAXQUEUETIME")]
        public System.Nullable<double> MaxQueueTime {
            get; set;
        }
        [Column("WARNINGQUEUETIME")]
        public System.Nullable<double> WarningQueueTime {
            get; set;
        }
        public virtual SpecBase Base {
            get; set;
        }
        [Column("SPECREVISION")]
        public string Revision {
            get; set;
        }
        [Column("STATUS")]
        public StatusEnum Status {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("SPECID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
        [Column("AUTODISASSOCIATE")]
        public System.Nullable<bool> AutoDisassociate {
            get; set;
        }
        public virtual IssueDifferenceReason DefaultIssueDifferenceReason {
            get; set;
        }
        [Column("AUTOCLOSE")]
        public System.Nullable<bool> AutoClose {
            get; set;
        }
        public virtual MfgLine MfgLine {
            get; set;
        }
        [Column("AUTOCOMPONENTISSUE")]
        public System.Nullable<bool> AutoComponentIssue {
            get; set;
        }
        [Column("ISMATERIALISSUE")]
        public System.Nullable<bool> IsMaterialIssue {
            get; set;
        }
    }
}
