//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description History information  that is common to most or all shop floor transaction services is stored in the HistoryMainline.  Typically there is one HistoryMainline entry for each Shop floor transaction, although compound transactions can be configured to generate multiple HistoryMainlines when appropriate.  The HistoryMainline is the primary source of History information.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [Table("HISTORYMAINLINE")]
    public class HistoryMainline : BaseObject {
        [Column("HISTORYMAINLINEID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("STATUS")]
        public StatusEnum Status {
            get; set;
        }
        [Column("TXNDATE")]
        public System.Nullable<System.DateTime> TxnDate {
            get; set;
        }
        [Column("SYSTEMDATE")]
        public System.Nullable<System.DateTime> SystemDate {
            get; set;
        }
        public virtual Factory Factory {
            get; set;
        }
        public virtual Employee Employee {
            get; set;
        }
        [Column("CLIENT")]
        public System.Nullable<int> Client {
            get; set;
        }
        [Column("SERVER")]
        public System.Nullable<int> Server {
            get; set;
        }
        public virtual Container Container {
            get; set;
        }
        public virtual Operation Operation {
            get; set;
        }
        public virtual Resource Resource {
            get; set;
        }
        [Column("COMMENTS")]
        public string Comments {
            get; set;
        }
        public virtual Owner Owner {
            get; set;
        }
        public virtual Product Product {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("INREWORK")]
        public System.Nullable<bool> InRework {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        public virtual SpecStep WorkflowStep {
            get; set;
        }
        public virtual Spec Spec {
            get; set;
        }
        [Column("TXNTYPENAME")]
        public string TxnTypeName {
            get; set;
        }
        public virtual Container ParentContainer {
            get; set;
        }
        [Column("PARENTCONTAINERNAME")]
        public string ParentContainerName {
            get; set;
        }
        [Column("TOQTY")]
        public System.Nullable<double> ToQty {
            get; set;
        }
        [Column("QTY")]
        public System.Nullable<double> Qty {
            get; set;
        }
        [Column("MOVEINQTY")]
        public System.Nullable<double> MoveInQty {
            get; set;
        }
        [Column("LASTMOVEOUTDATE")]
        public System.Nullable<System.DateTime> LastMoveOutDate {
            get; set;
        }
        [Column("TXNSEQUENCE")]
        public System.Nullable<int> TxnSequence {
            get; set;
        }
        [Column("CHILDCOUNT")]
        public System.Nullable<int> ChildCount {
            get; set;
        }
        [Column("CONTAINERNAME")]
        public string ContainerName {
            get; set;
        }
        [Column("MOVEINDATE")]
        public System.Nullable<System.DateTime> MoveInDate {
            get; set;
        }
        [Column("SERVERNAME")]
        public string ServerName {
            get; set;
        }
        [Column("COMPUTERNAME")]
        public string ComputerName {
            get; set;
        }
    }
}
