//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/23
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("SPECBASE")]
    public class SpecBase : BusinessProcessSpecBase {
        [Column("SPECNAME")]
        public new string Name {
            get; set;
        }
        [Column("ICONID")]
        public new System.Nullable<int> IconId {
            get; set;
        }
        public new virtual Spec RevOfRcd {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public new System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("SPECBASEID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        [Column("CDOTYPEID")]
        public new System.Nullable<int> CDOTypeId {
            get; set;
        }
    }
}
