//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description Manufacturing Line is used to represent the line where containers are being processed. It can be assigned to Spec, Resource, Container and Mfg Order. It is used during manufacturing line verification when a container start production or more accurately moves out of a Spec with its Verify Mfg Line set to true. The Container's Mfg Line will be taken from its own Mfg Line field, Mfg Order's Mfg Line or the current Spec's Mfg Line. Once determined the verification will check all steps within the Container's Workflow with the same Mfg Line.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [Table("A_MFGLINE")]
    public class MfgLine : ES_NDOs {
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("MFGLINEID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("MFGLINENAME")]
        public string Name {
            get; set;
        }
    }
}
