//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/23
//
namespace CamstarClient.Entity {
    
    public enum IssueControlEnum {
        Serialized = 1,
        Bulk = 2,
        LotAndStockPoint = 3,
        StockPointOnly = 4,
        NoTracking = 5,
        CommentOnly = 6,
    }
}
