//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description A Workflow defines the route and processing required for a process, 
///
///A Workflow is a collection of Steps that are linked by Paths, Steps reference either other Workflows or Specs
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [NotMapped()]
    public abstract class BusinessProcessWorkflow : RevisionedObject {
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        public string InstanceID {
            get; set;
        }
        public System.Nullable<int> ChangeCount {
            get; set;
        }
    }
}
