//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description A specification (Spec) describes the processing that takes place at a Step within a Workflow. It references many other Modeling components.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [NotMapped()]
    public abstract class BusinessProcessSpec : RevisionedObject {
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        public string InstanceID {
            get; set;
        }
        public System.Nullable<int> ChangeCount {
            get; set;
        }
    }
}
