//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description A Product is typically a definition of what kind of material needs to be provided to a customer or what kind of material is being used as a raw material or other component in a manufacturing process.  Products can belong to a Product Family. A product to be manufactured will have an associated Workflow. Attributes of the Workflow may be overridden to be product specific.
///
///Optionally, a Product can belong to a Product Family. A Product Family is used to group products for the purpose of simplifying the maintenance task (for modeling data). Common attributes such as costing or processing information can then be provided for a Product Family and applied to each Product within the family.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [Table("PRODUCT")]
    public class Product : RevisionedObject {
        public virtual ProductFamily ProductFamily {
            get; set;
        }
        public virtual ProductType ProductType {
            get; set;
        }
        public virtual Workflow Workflow {
            get; set;
        }
        public virtual Customer Customer {
            get; set;
        }
        [Column("PRODUCTREVISION")]
        public string Revision {
            get; set;
        }
        public virtual UOM StdStartUOM {
            get; set;
        }
        public virtual ProductBase Base {
            get; set;
        }
        [Column("STATUS")]
        public StatusEnum Status {
            get; set;
        }
        [Column("ISFROZEN")]
        public System.Nullable<bool> IsFrozen {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("PRODUCTID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
        [Column("OBJECTCATEGORY")]
        public string ObjectCategory {
            get; set;
        }
        public virtual ContainerLevel StdStartLevel {
            get; set;
        }
        public virtual Factory StdStartFactory {
            get; set;
        }
        public virtual Owner StdStartOwner {
            get; set;
        }
        [Column("OBJECTTYPE")]
        public string ObjectType {
            get; set;
        }
        public virtual Customer StdStartCustomer {
            get; set;
        }
        [Column("MFGORDERREQUIRED")]
        public System.Nullable<bool> MfgOrderRequired {
            get; set;
        }
        public virtual StartReason StdStartReason {
            get; set;
        }
    }
}
