//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("WORKFLOW")]
    public class Workflow : BusinessProcessWorkflow {
        public new virtual Step FirstStep {
            get; set;
        }
        public new virtual WorkflowBase Base {
            get; set;
        }
        [Column("WORKFLOWID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
    }
}
