//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description A Named Object Group that represents a group of Resources.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [Table("RESOURCEGROUP")]
    public class ResourceGroup : NamedObjectGroup {
        public virtual ICollection<Resource> Entries {
            get; set;
        }
        public virtual ICollection<ResourceGroup> Groups {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("RESOURCEGROUPNAME")]
        public string Name {
            get; set;
        }
        [Column("ENTRYTYPE")]
        public string EntryType {
            get; set;
        }
        [Column("RESOURCEGROUPID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
        [Column("OBJECTCATEGORY")]
        public string ObjectCategory {
            get; set;
        }
        [Column("OBJECTTYPE")]
        public string ObjectType {
            get; set;
        }
    }
}
