//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CamstarDb.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using Microsoft.EntityFrameworkCore;

///    @Description The user code for container defect reason.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarDb.Entities
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using global::CamstarDb.Entities.Enum;

    [Table("CONTAINERDEFECTREASON")]
    public class ContainerDefectReason : UserCode {
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("DEFECTREASONNAME")]
        public string Name {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("DEFECTREASONID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
    }
}

namespace CamstarDb.Context
{
    public partial class CamstarDbContext : DbContext
    {
        public DbSet<ContainerDefectReason> ContainerDefectReasons { get; set; }
    }
    public class ContainerDefectReasonEntityTypeConfiguration : IEntityTypeConfiguration<ContainerDefectReason>
    {
        public void Configure(EntityTypeBuilder<ContainerDefectReason> builder)
        {

        }
    }
}