//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description The reason material was removed from a WIP container
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarDb.Entities
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using global::CamstarDb.Entities.Enum;

    [Table("REMOVALREASON")]
    public class RemovalReason : UserCode {
        [Column("REMOVALREASONID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("REMOVALREASONNAME")]
        public string Name {
            get; set;
        }
        [Column("REMOVALTYPE")]
        public System.Nullable<int> RemovalType {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
    }
}
