//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CamstarDb.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using Microsoft.EntityFrameworkCore;

///    @Description The user code for loss reason.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarDb.Entities
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using global::CamstarDb.Entities.Enum;

    [Table("TRAININGRECORDSTATUS")]
    public class TrainingRecordStatus : UserCode {
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("TRAININGRECORDSTATUSNAME")]
        public string Name {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("TRAININGRECORDSTATUSID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
    }
}
namespace CamstarDb.Context
{
    public partial class CamstarDbContext : DbContext
    {
        public DbSet<TrainingRecordStatus> TrainingRecordStatuss { get; set; }
    }
    public class TrainingRecordStatusEntityTypeConfiguration : IEntityTypeConfiguration<TrainingRecordStatus>
    {
        public void Configure(EntityTypeBuilder<TrainingRecordStatus> builder)
        {

        }
    }
}
