//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description ERP Production Order status.  Can include values like "Released", "Completed", "In Process", "Closed", "Cancelled"
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [Table("ORDERSTATUS")]
    public class OrderStatus : UserCode {
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("ORDERSTATUSID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("ORDERSTATUSNAME")]
        public string Name {
            get; set;
        }
        [Column("ISORDERSTATES")]
        public isOrderStateEnum isOrderStates {
            get; set;
        }
        [Column("ISCONFIRMED")]
        public System.Nullable<bool> IsConfirmed {
            get; set;
        }
    }
}
