//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/22
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("PRODUCT")]
    public class Product : RevisionedObject {
        public virtual ProductType ProductType {
            get; set;
        }
        public virtual Workflow Workflow {
            get; set;
        }
        public virtual Customer Customer {
            get; set;
        }
        public virtual UOM StdStartUOM {
            get; set;
        }
        public new virtual ProductBase Base {
            get; set;
        }
        
        [Column("PRODUCTID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        [Column("OBJECTCATEGORY")]
        public string ObjectCategory {
            get; set;
        }
        public virtual ContainerLevel StdStartLevel {
            get; set;
        }
        public virtual Factory StdStartFactory {
            get; set;
        }
        public virtual Owner StdStartOwner {
            get; set;
        }
        [Column("OBJECTTYPE")]
        public string ObjectType {
            get; set;
        }
        public virtual Customer StdStartCustomer {
            get; set;
        }
        [Column("MFGORDERREQUIRED")]
        public bool MfgOrderRequired {
            get; set;
        }
        public virtual StartReason StdStartReason {
            get; set;
        }
    }
}
