//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//    @author lichong
//    @date 2024/3/23
//
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("PRODUCT")]
    public class Product : RevisionedObject {
        public virtual ProductFamily ProductFamily {
            get; set;
        }
        public virtual ProductType ProductType {
            get; set;
        }
        public virtual Workflow Workflow {
            get; set;
        }
        public virtual Customer Customer {
            get; set;
        }
        [Column("PRODUCTREVISION")]
        public new string Revision {
            get; set;
        }
        public virtual UOM StdStartUOM {
            get; set;
        }
        public new virtual ProductBase Base {
            get; set;
        }
        [Column("STATUS")]
        public new StatusEnum Status {
            get; set;
        }
        [Column("ISFROZEN")]
        public new System.Nullable<bool> IsFrozen {
            get; set;
        }
        [Column("DESCRIPTION")]
        public new string Description {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public new System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("PRODUCTID")]
        [Key()]
        public new string InstanceID {
            get; set;
        }
        [Column("CDOTYPEID")]
        public new System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public new string Notes {
            get; set;
        }
        [Column("OBJECTCATEGORY")]
        public string ObjectCategory {
            get; set;
        }
        public virtual ContainerLevel StdStartLevel {
            get; set;
        }
        public virtual Factory StdStartFactory {
            get; set;
        }
        public virtual Owner StdStartOwner {
            get; set;
        }
        [Column("OBJECTTYPE")]
        public string ObjectType {
            get; set;
        }
        public virtual Customer StdStartCustomer {
            get; set;
        }
        [Column("MFGORDERREQUIRED")]
        public System.Nullable<bool> MfgOrderRequired {
            get; set;
        }
        public virtual StartReason StdStartReason {
            get; set;
        }
    }
}
