//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description A User Code Object Group that represents a group of Buy Reasons.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarDb.Entities {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using global::CamstarDb.Entities.Enum;
    
    [Table("BUYREASONGROUP")]
    public class BuyReasonGroup : UserCodeGroup {
        [Column("BUYREASONGROUPID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("BUYREASONGROUPNAME")]
        public string Name {
            get; set;
        }
        public virtual ICollection<BuyReason> Entries {
            get; set;
        }
        [Column("ENTRYTYPE")]
        public string EntryType {
            get; set;
        }
        public virtual ICollection<BuyReasonGroup> Groups {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
    }
}
