//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description A User Code Object Group that represents a group of Quantity Adjust Reasons.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarDbClient.CamstarEntities {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarDbClient.CamstarEntities.Enum;
    
    [Table("QTYADJUSTGROUP")]
    public class QtyAdjustReasonGroup : UserCodeGroup {
        [Column("QTYADJUSTGROUPID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("QTYADJUSTGROUPNAME")]
        public string Name {
            get; set;
        }
        public virtual ICollection<QtyAdjustReason> Entries {
            get; set;
        }
        [Column("ENTRYTYPE")]
        public string EntryType {
            get; set;
        }
        public virtual ICollection<QtyAdjustReasonGroup> Groups {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
    }
}
