//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CamstarDb.Entities;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using Microsoft.EntityFrameworkCore;

///    @Description A User Code Object Group that represents a group of Buy Reasons.
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarDb.Entities
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("REWORKREASONGROUP")]
    public class ReworkReasonGroup : UserCodeGroup {
        [Column("REWORKREASONGROUPID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("REWORKREASONGROUPNAME")]
        public string Name {
            get; set;
        }
        public virtual ICollection<ReworkReason> Entries {
            get; set;
        }
        [Column("ENTRYTYPE")]
        public string EntryType {
            get; set;
        }
        public virtual ICollection<ReworkReasonGroup> Groups {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }

        public virtual ICollection<ReworkReasonGroup> ReworkReasonGroups { get; set; }
    }
}
namespace CamstarDb.Context
{
    public partial class CamstarDbContext : DbContext
    {
        public DbSet<ReworkReasonGroup> ReworkReasonGroups { get; set; }
    }
    public class ReworkReasonGroupEntityTypeConfiguration : IEntityTypeConfiguration<ReworkReasonGroup>
    {
        public void Configure(EntityTypeBuilder<ReworkReasonGroup> builder)
        {
            builder.HasMany(e => e.Groups).WithMany(e => e.ReworkReasonGroups).UsingEntity<Dictionary<string, object>>(
               "NAMEDOBJECTGROUPGROUPS",
               l => l.HasOne<ReworkReasonGroup>().WithMany().HasForeignKey("GROUPSID"),
               r => r.HasOne<ReworkReasonGroup>().WithMany().HasForeignKey("NAMEDOBJECTGROUPID"),
               j =>
               {
                   j.HasKey("NAMEDOBJECTGROUPID", "GROUPSID");
               }
                );

            builder.HasMany(e => e.Entries).WithMany(e => e.ReworkReasonGroups)
            .UsingEntity<Dictionary<string, object>>(
                "NAMEDOBJECTGROUPENTRIES",
                l => l.HasOne<ReworkReason>().WithMany().HasForeignKey("ENTRIESID"),
                r => r.HasOne<ReworkReasonGroup>().WithMany().HasForeignKey("NAMEDOBJECTGROUPID"),
                j =>
                {
                    j.HasKey("NAMEDOBJECTGROUPID", "ENTRIESID");
                }
            );
        }
    }
}