//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

///    @Description A Manufacturing Order is a request to manufacture a product. Manufacturing orders are typically originated to fulfill a sales order or inventory requirements and are often a link between MES and an ERP system. 
///
///A Manufacturing Order can contain a list of product containers. The relationship of a container to a manufacturing order is established and maintained in the containers data record. This information is used to provide WIP status by manufacturing order and WIP updates to the ERP system.
///
///
///    @author lichong
///    @date 2024/3/24
///
namespace CamstarClient.Entity {
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using CamstarClient.Enum;
    
    [Table("MFGORDER")]
    public class MfgOrder : NamedDataObject {
        [Column("QTY")]
        public System.Nullable<double> Qty {
            get; set;
        }
        public virtual Product Product {
            get; set;
        }
        public virtual UOM UOM {
            get; set;
        }
        [Column("MFGORDERID")]
        [Key()]
        public string InstanceID {
            get; set;
        }
        [Column("MFGORDERNAME")]
        public string Name {
            get; set;
        }
        [Column("DESCRIPTION")]
        public string Description {
            get; set;
        }
        [Column("CHANGECOUNT")]
        public System.Nullable<int> ChangeCount {
            get; set;
        }
        [Column("CDOTYPEID")]
        public System.Nullable<int> CDOTypeId {
            get; set;
        }
        [Column("NOTES")]
        public string Notes {
            get; set;
        }
        [Column("PLANNEDSTARTDATE")]
        public System.Nullable<System.DateTime> PlannedStartDate {
            get; set;
        }
        [Column("PLANNEDCOMPLETIONDATE")]
        public System.Nullable<System.DateTime> PlannedCompletionDate {
            get; set;
        }
        [Column("RELEASEDATE")]
        public System.Nullable<System.DateTime> ReleaseDate {
            get; set;
        }
        public virtual OrderType OrderType {
            get; set;
        }
        public virtual OrderStatus OrderStatus {
            get; set;
        }
        [Column("QTYSTARTED")]
        public System.Nullable<double> QtyStarted {
            get; set;
        }
        [Column("LASTCHANGEDATE")]
        public System.Nullable<System.DateTime> LastChangeDate {
            get; set;
        }
        public virtual MfgLine MfgLine {
            get; set;
        }
    }
}
